language: node_js

cache:
  directories:
  - ~/.npm

node_js:
- '10'

before_install:
- npm i -g npm@latest

install:
- npm ci

script:
- npm run cloc
- npm run jscpd
- npm run tslint
- npm run build

after_success:
- npm run travis-deploy-once "npm run semantic-release"
