language: node_js

cache:
  directories:
  - ~/.npm

notifications:
  email: false

node_js:
- '10'

install:
- npm ci

script:
- commitlint-travis
- npm run cloc
- npm run jscpd
- npm run tslint
- npm run build

after_success:
- npm run travis-deploy-once "npm run semantic-release"

branches:
  except:
  - /^v\d+\.\d+\.\d+$/
